AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dynamic DNS Management System with AWS Route 53

Parameters:
  AdminUsername:
    Type: String
    Default: admin
    Description: Admin username for initial setup

  AdminPassword:
    Type: String
    NoEcho: true
    Description: Admin password for initial setup

  AppSecret:
    Type: String
    NoEcho: true
    Description: Secret for session signing (32 bytes recommended)

  DomainName:
    Type: String
    Default: DISABLED
    Description: Custom domain name for the application (or DISABLED)

  HostedZoneId:
    Type: String
    Default: DISABLED
    Description: Route53 Hosted Zone ID for custom domain (or DISABLED)

  CloudFrontCertificateArn:
    Type: String
    Default: DISABLED
    Description: ARN of ACM certificate in us-east-1 for CloudFront (or DISABLED)

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref DomainName, DISABLED]]

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Runtime: provided.al2023
    Architectures:
      - arm64

Resources:
  # DynamoDB Table - Single table design
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # Lambda Function
  DDNSFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/lambda/
      Handler: bootstrap
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
          ADMIN_USERNAME: !Ref AdminUsername
          ADMIN_PASSWORD: !Ref AdminPassword
          APP_SECRET: !Ref AppSecret
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - route53:ListHostedZones
                - route53:GetHostedZone
                - route53:ListResourceRecordSets
                - route53:ChangeResourceRecordSets
              Resource: '*'
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi

  # HTTP API Gateway
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Content-Type
          - X-CSRF-Token
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE

  # Custom Domain (conditional)
  ApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: HasCustomDomain
    Properties:
      DomainName: !Ref DomainName
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: !Ref CloudFrontCertificateArn

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Condition: HasCustomDomain
    Properties:
      ApiId: !Ref HttpApi
      DomainName: !Ref DomainName
      Stage: $default
    DependsOn: ApiDomainName

  Route53Record:
    Type: AWS::Route53::RecordSet
    Condition: HasCustomDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiDomainName.RegionalDomainName
        HostedZoneId: !GetAtt ApiDomainName.RegionalHostedZoneId
    DependsOn: ApiDomainName

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com

  CustomDomainEndpoint:
    Description: Custom domain endpoint (if configured)
    Condition: HasCustomDomain
    Value: !Sub https://${DomainName}

  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref DynamoDBTable
